/*
 * ultrasonic_sensor.c
 *
 *  Created on: 11 Oct 2022
 *      Author: Elsheriif
 */

#include "ultrasonic_sensor.h"
#include"icu.h"
#include"gpio.h"
#include"util/delay.h"



/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
/*Global variable to store the distance read by the sensor*/
static volatile uint16 g_distance = 0;
/* Get High Count */
static volatile uint16 g_highTimeCount =0;
/* Get edge count*/
static volatile uint8 g_edgeCount=0;

/* Store the Period time value */
static volatile uint16 g_timePeriod = 0;

/* Store the Period time value + High time value */
static volatile uint16 g_timePeriodPlusHigh = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * 	Initialize the ICU driver as required.
 * 	Setup the ICU call back function.
 * 	Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	/* Initialize ICU */
	Icu_init(&Icu_Config);

	/* Setup ICU CallBack Function*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Setting the Trigger Pin as Output*/
	GPIO_setupPinDirection(TRIGGER_PORT_ID, TRIGGER_PIN_ID, PIN_OUTPUT);


	/*Echo Pin is used with ICU, made as input inside ICU init */
}



/*
 * Description :
 * 	Send the Trigger pulse to the ultrasonic
 * 	transmit at least 10 us trigger pulse to the HC-SR04 Trig Pin
 * 	After getting a trigger pulse, HC-SR04 automatically sends eight 40 kHz sound
 *  waves and the microcontroller waits for rising edge output at the Echo pin.
 */
void Ultrasonic_Trigger(void)
{
	/* Must Transmit 10us pulse to Trigger Pin	*/
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID, TRIGGER_PIN_ID, LOGIC_LOW);

	/* After this the sensor will automatically send 8 40Khz(250us) pulses
	 * Then in will Generate Rising Edge on Echo pin (ICU PIN)
	 */
}


/*
 * Description :
 *  Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void)
{
	/*	Send Trigger 10us Signal */
	Ultrasonic_Trigger();

	/* Wait until High Time is achieved to measure distance in cm*/

	if(g_edgeCount==4)
	{
		g_edgeCount=0;
		g_highTimeCount=0;

		g_distance = ( g_timePeriodPlusHigh - g_timePeriod ) / 58;  /* (High_Time) / 58 */

	}
	return g_distance;
}


/*
 * Description :
 *  This is the call back function called by the ICU driver.
 * 	This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{

	g_edgeCount++;
	if(g_edgeCount==1)	   /*	First Rising Edge Detected */
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();

		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount==2)   	/* First Falling Edge detected ,so get high time value*/
	{
		/* Store the High time value */
		g_highTimeCount=Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
	else if(g_edgeCount==3)
	{
		/* Store the Period time value */
		g_timePeriod = Icu_getInputCaptureValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 4)
	{
		/* Store the Period time value + High time value */
		g_timePeriodPlusHigh = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}

}


