/*
 * ultrasonic_sesnor.h
 *
 *  Created on: 11 Oct 2022
 *      Author: Elsheriif
 */

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include"std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TRIGGER_PORT_ID   	PORTB_ID
#define TRIGGER_PIN_ID		PIN5_ID



/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/


/*
 * Description :
 * 	Initialize the ICU driver as required.
 * 	Setup the ICU call back function.
 * 	Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);



/*
 * Description :
 * 	Send the Trigger pulse to the ultrasonic
 * 	transmit at least 10 us trigger pulse to the HC-SR04 Trig Pin
 * 	After getting a trigger pulse, HC-SR04 automatically sends eight 40 kHz sound
 *  waves and the microcontroller waits for rising edge output at the Echo pin.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
 *  Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void);


/*
 * Description :
 *  This is the call back function called by the ICU driver.
 * 	This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);





#endif /* ULTRASONIC_SENSOR_H_ */
